# APP Port
server:
  port: 8080

spring:
  # Profile
  profiles:
    active: dev
  # Banner
  banner:
    location: Banner.txt
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/agv}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        type:
          wrapper_array_handling: ALLOW
    database: postgresql

# MQTT
mqtt:
  broker-url: ${BROKER_URL:tcp://localhost:1883}

# JWT
jwt:
  key: ffEhtpE5/lfABdWIg7q6brJodYfmo/oig+3GLc/SN68xsEzsAnbqsIwEjjd3NYNxiycTTNsNUOWHSZQy1pLz7MzROT+VQ1ZOnQLHj2T79DcJV5rxr0LvbzgYWqEjz9PmiZkppWbaf0yGa3ZZFNHEsoc/5ni4Ii6liXyr2wEE8jo=
  expiration: 2147483647

# Project Description
application:
  title: 'YIGIDO AGV BACKEND'
  version: 'v1.0'